#!/bin/zsh

###############################################################################
# setup-brew
#
# A shell script to automate system tool setup for Mac OS X.
###############################################################################


###############################################################################
# Install Xcode command line tools
###############################################################################
echo "Installing Xcode Command Line Tools..."
xcode-select --install


###############################################################################
# Check for Homebrew, else install
###############################################################################
echo "Checking for, or Installing Homebrew..."
if [ -z `command -v brew` ]; then
    echo "Brew is missing! Installing it..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi;


###############################################################################
# Make sure we're on latest Homebrew
###############################################################################
echo "Homebrew: updating..."
brew update


###############################################################################
# Upgrade any already-installed formulae
###############################################################################
echo "Homebrew: upgrading..."
brew upgrade


###############################################################################
# Install utilities
###############################################################################
echo "Homebrew: updating unix tools..."
brew install zsh
brew install homebrew/cask-fonts/font-fira-mono-for-powerline


###############################################################################
# Install binaries and other packages
###############################################################################
echo "Homebrew: installing binaries and other packages..."
brew install ffmpeg
brew install git
brew install heroku/brew/heroku
brew install httpie
brew install imagemagick
brew install mackup
brew install mas
brew install nginx
brew install node
brew install nvm
brew install rename
brew install tree
brew install webkit2png
brew install yarn


###############################################################################
# Run Homebrew cleanup to remove installation/cached files
###############################################################################
echo "Homebrew: cleaning up..."
brew cleanup


###############################################################################
# Install Node Packages with NPM
###############################################################################
echo "Node: installing Yarn/NPM packages…"
yarn global add @sanity/cli
yarn global add @squarespace/server
yarn global add contentful-cli
yarn global add firebase-tools
yarn global add http-server
yarn global add imageoptim-cli
yarn global add js-beautify
yarn global add markdown-pdf
yarn global add netlify-cli
yarn global add now
yarn global add svgo


###############################################################################
# Install applications with Homebrew Cask
###############################################################################
echo "Homebrew Cask: installing apps..."
brew install --cask 1password
brew install --cask ableton-live-suite
brew install --cask adobe-creative-cloud
brew install --cask alfred
brew install --cask dash
brew install --cask docker
# brew install --cask dropbox
brew install --cask figma
brew install --cask firefox
brew install --cask framer-x
brew install --cask github
brew install --cask google-chrome
brew install --cask google-cloud-sdk
brew install --cask google-drive-file-stream
brew install --cask hyper
brew install --cask imageoptim
brew install --cask iina
brew install --cask iterm2
brew install --cask notion
brew install --cask nucleo
brew install --cask obs
brew install --cask postman
brew install --cask screenflow
brew install --cask skype
brew install --cask slack
brew install --cask spectacle
brew install --cask spotify
brew install --cask sourcetree
brew install --cask tor-browser
brew install --cask transmit
brew install --cask tunnelbear
brew install --cask visual-studio-code
brew install --cask whatsapp


###############################################################################
# Execute installers downloaded with Homebrew Cask
###############################################################################
echo "Opening installers..."

echo "Opening Installer: Adobe Creative Cloud"
open /usr/local/Caskroom/adobe-creative-cloud/latest/Creative\ Cloud\ Installer.app/


###############################################################################
# Cleanup
###############################################################################
brew cleanup


###############################################################################
# Install applications with mas-cli (Mac App Store CLI)
###############################################################################
echo "mas-cli: installing Mac App Store apps..."
# Amphetamine
mas install 937984704
# DaisyDisk
mas install 411643860
# JPEGmini
mas install 498944723
# Mactracker
mas install 430255202
# Sip
mas install 507257563
# Speedtest
mas install 1153157709
# Twitter
mas install 1482454543
# WiFi Explorer
mas install 494803304


echo "macOS Config, Dev Tools, Apps are Done Setup!"
